//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    using System.ServiceModel;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.BatchSyncStatusRequestBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetBatchSyncEmployeesStatusRqt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.BatchSyncEmployeesRqt))]
    public partial class RequestBase : object
    {
        
        private string AuthenticationTokenField;
        
        private int CustomerIdField;
        
        private ServiceReference1.RemotableIdOfint DepartmentIdField;
        
        private bool IncludeDebugOverviewField;
        
        private string ReferenceTokenField;
        
        private ServiceReference1.SystemLanguageTypes SystemLanguageTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthenticationToken
        {
            get
            {
                return this.AuthenticationTokenField;
            }
            set
            {
                this.AuthenticationTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeDebugOverview
        {
            get
            {
                return this.IncludeDebugOverviewField;
            }
            set
            {
                this.IncludeDebugOverviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceToken
        {
            get
            {
                return this.ReferenceTokenField;
            }
            set
            {
                this.ReferenceTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SystemLanguageTypes SystemLanguageType
        {
            get
            {
                return this.SystemLanguageTypeField;
            }
            set
            {
                this.SystemLanguageTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemotableIdOfint", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class RemotableIdOfint : object
    {
        
        private int IdField;
        
        private string ThirdPartyIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdPartyId
        {
            get
            {
                return this.ThirdPartyIdField;
            }
            set
            {
                this.ThirdPartyIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncStatusRequestBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetBatchSyncEmployeesStatusRqt))]
    public partial class BatchSyncStatusRequestBase : ServiceReference1.RequestBase
    {
        
        private string InitialReferenceTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InitialReferenceToken
        {
            get
            {
                return this.InitialReferenceTokenField;
            }
            set
            {
                this.InitialReferenceTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBatchSyncEmployeesStatusRqt", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class GetBatchSyncEmployeesStatusRqt : ServiceReference1.BatchSyncStatusRequestBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncEmployeesRqt", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class BatchSyncEmployeesRqt : ServiceReference1.RequestBase
    {
        
        private bool DoNotDeleteUnlistedSynchronizedEmployeesField;
        
        private ServiceReference1.Employee[] EmployeeListField;
        
        private bool NewEmployeeMustChangePasswordOnFirstSignInField;
        
        private bool PlaceEmployeeOnRootIfAccessDepartmentDoesNotExistField;
        
        private bool SendSignInInfoToNewEmployeesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DoNotDeleteUnlistedSynchronizedEmployees
        {
            get
            {
                return this.DoNotDeleteUnlistedSynchronizedEmployeesField;
            }
            set
            {
                this.DoNotDeleteUnlistedSynchronizedEmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.Employee[] EmployeeList
        {
            get
            {
                return this.EmployeeListField;
            }
            set
            {
                this.EmployeeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NewEmployeeMustChangePasswordOnFirstSignIn
        {
            get
            {
                return this.NewEmployeeMustChangePasswordOnFirstSignInField;
            }
            set
            {
                this.NewEmployeeMustChangePasswordOnFirstSignInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PlaceEmployeeOnRootIfAccessDepartmentDoesNotExist
        {
            get
            {
                return this.PlaceEmployeeOnRootIfAccessDepartmentDoesNotExistField;
            }
            set
            {
                this.PlaceEmployeeOnRootIfAccessDepartmentDoesNotExistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendSignInInfoToNewEmployees
        {
            get
            {
                return this.SendSignInInfoToNewEmployeesField;
            }
            set
            {
                this.SendSignInInfoToNewEmployeesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemLanguageTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum SystemLanguageTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NorwegianBokmal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swedish = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Danish = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finnish = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        German = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        French = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NorwegianNynorsk = 18,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class Employee : ServiceReference1.RemotableEntityBase
    {
        
        private ServiceReference1.EmployeeDetails DetailsField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeDetails Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemotableEntityBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Employee))]
    public partial class RemotableEntityBase : object
    {
        
        private ServiceReference1.RemotableIdOfint IdField;
        
        private ServiceReference1.RemotableIdOfint ParentDepartmentIdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint ParentDepartmentId
        {
            get
            {
                return this.ParentDepartmentIdField;
            }
            set
            {
                this.ParentDepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class EmployeeDetails : object
    {
        
        private ServiceReference1.UserAccessInfo[] AccessLevelListField;
        
        private string AddressField;
        
        private string Address2Field;
        
        private string AlternateEmailField;
        
        private System.Nullable<System.DateTime> AnniversaryDateField;
        
        private string AppraisalImageFileNameField;
        
        private System.Nullable<System.DateTime> AvailabilityDateField;
        
        private string BankAccountNumberField;
        
        private string BankRegistrationNumberField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string CityField;
        
        private string CostCenterField;
        
        private string CountryField;
        
        private ServiceReference1.RemotableIdOfint EducationLevelIdField;
        
        private System.Nullable<System.DateTime> EmploymentDateField;
        
        private System.Nullable<System.DateTime> EmploymentEndDateField;
        
        private string EmploymentIdField;
        
        private double FTEField;
        
        private ServiceReference1.GenderTypes GenderField;
        
        private ServiceReference1.RemotableIdOfint JobTitleIdField;
        
        private ServiceReference1.RemotableIdOfint JobTypeIdField;
        
        private ServiceReference1.EmployeeKeyInformationAnswer[] KeyInformationAnswerListField;
        
        private string LastName2Field;
        
        private System.Nullable<System.DateTime> LastWorkingDateField;
        
        private ServiceReference1.RemotableIdOfint MaritalStatusIdField;
        
        private string NationalityField;
        
        private ServiceReference1.RemotableIdOfint NoticeTimeIdField;
        
        private ServiceReference1.RemotableIdOfint ParentEmployeeField;
        
        private int ParentEmployeeIdField;
        
        private string PersonIdField;
        
        private string PhoneFaxField;
        
        private string PhoneMobileField;
        
        private string PhoneMobileCountryCodeField;
        
        private string PhonePrivateField;
        
        private string PhonePrivateCountryCodeField;
        
        private string PhoneWorkField;
        
        private string PhoneWorkCountryCodeField;
        
        private int ProbationPeriodIdField;
        
        private ServiceReference1.RemotableIdOfint ReasonForLeavingIdField;
        
        private string RelativeInfo1EmailField;
        
        private string RelativeInfo1NameField;
        
        private string RelativeInfo1PhoneField;
        
        private ServiceReference1.RemotableIdOfint RelativeInfo1RelationIdField;
        
        private string RelativeInfo2EmailField;
        
        private string RelativeInfo2NameField;
        
        private string RelativeInfo2PhoneField;
        
        private ServiceReference1.RemotableIdOfint RelativeInfo2RelationIdField;
        
        private System.Nullable<System.DateTime> ResignationDateField;
        
        private string SalaryField;
        
        private System.Nullable<System.DateTime> SeniorityDateField;
        
        private string StaffCategoryField;
        
        private string ThirdPartyUsernameField;
        
        private string WorkLocationField;
        
        private int WorkPercentageField;
        
        private int WorkTimeEndField;
        
        private int WorkTimeStartField;
        
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.UserAccessInfo[] AccessLevelList
        {
            get
            {
                return this.AccessLevelListField;
            }
            set
            {
                this.AccessLevelListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternateEmail
        {
            get
            {
                return this.AlternateEmailField;
            }
            set
            {
                this.AlternateEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AnniversaryDate
        {
            get
            {
                return this.AnniversaryDateField;
            }
            set
            {
                this.AnniversaryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppraisalImageFileName
        {
            get
            {
                return this.AppraisalImageFileNameField;
            }
            set
            {
                this.AppraisalImageFileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AvailabilityDate
        {
            get
            {
                return this.AvailabilityDateField;
            }
            set
            {
                this.AvailabilityDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber
        {
            get
            {
                return this.BankAccountNumberField;
            }
            set
            {
                this.BankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankRegistrationNumber
        {
            get
            {
                return this.BankRegistrationNumberField;
            }
            set
            {
                this.BankRegistrationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                this.CostCenterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint EducationLevelId
        {
            get
            {
                return this.EducationLevelIdField;
            }
            set
            {
                this.EducationLevelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmploymentDate
        {
            get
            {
                return this.EmploymentDateField;
            }
            set
            {
                this.EmploymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmploymentEndDate
        {
            get
            {
                return this.EmploymentEndDateField;
            }
            set
            {
                this.EmploymentEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentId
        {
            get
            {
                return this.EmploymentIdField;
            }
            set
            {
                this.EmploymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FTE
        {
            get
            {
                return this.FTEField;
            }
            set
            {
                this.FTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.GenderTypes Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint JobTitleId
        {
            get
            {
                return this.JobTitleIdField;
            }
            set
            {
                this.JobTitleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint JobTypeId
        {
            get
            {
                return this.JobTypeIdField;
            }
            set
            {
                this.JobTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeKeyInformationAnswer[] KeyInformationAnswerList
        {
            get
            {
                return this.KeyInformationAnswerListField;
            }
            set
            {
                this.KeyInformationAnswerListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName2
        {
            get
            {
                return this.LastName2Field;
            }
            set
            {
                this.LastName2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastWorkingDate
        {
            get
            {
                return this.LastWorkingDateField;
            }
            set
            {
                this.LastWorkingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint MaritalStatusId
        {
            get
            {
                return this.MaritalStatusIdField;
            }
            set
            {
                this.MaritalStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint NoticeTimeId
        {
            get
            {
                return this.NoticeTimeIdField;
            }
            set
            {
                this.NoticeTimeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint ParentEmployee
        {
            get
            {
                return this.ParentEmployeeField;
            }
            set
            {
                this.ParentEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentEmployeeId
        {
            get
            {
                return this.ParentEmployeeIdField;
            }
            set
            {
                this.ParentEmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneFax
        {
            get
            {
                return this.PhoneFaxField;
            }
            set
            {
                this.PhoneFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMobile
        {
            get
            {
                return this.PhoneMobileField;
            }
            set
            {
                this.PhoneMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMobileCountryCode
        {
            get
            {
                return this.PhoneMobileCountryCodeField;
            }
            set
            {
                this.PhoneMobileCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhonePrivate
        {
            get
            {
                return this.PhonePrivateField;
            }
            set
            {
                this.PhonePrivateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhonePrivateCountryCode
        {
            get
            {
                return this.PhonePrivateCountryCodeField;
            }
            set
            {
                this.PhonePrivateCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneWork
        {
            get
            {
                return this.PhoneWorkField;
            }
            set
            {
                this.PhoneWorkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneWorkCountryCode
        {
            get
            {
                return this.PhoneWorkCountryCodeField;
            }
            set
            {
                this.PhoneWorkCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProbationPeriodId
        {
            get
            {
                return this.ProbationPeriodIdField;
            }
            set
            {
                this.ProbationPeriodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint ReasonForLeavingId
        {
            get
            {
                return this.ReasonForLeavingIdField;
            }
            set
            {
                this.ReasonForLeavingIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo1Email
        {
            get
            {
                return this.RelativeInfo1EmailField;
            }
            set
            {
                this.RelativeInfo1EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo1Name
        {
            get
            {
                return this.RelativeInfo1NameField;
            }
            set
            {
                this.RelativeInfo1NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo1Phone
        {
            get
            {
                return this.RelativeInfo1PhoneField;
            }
            set
            {
                this.RelativeInfo1PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint RelativeInfo1RelationId
        {
            get
            {
                return this.RelativeInfo1RelationIdField;
            }
            set
            {
                this.RelativeInfo1RelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo2Email
        {
            get
            {
                return this.RelativeInfo2EmailField;
            }
            set
            {
                this.RelativeInfo2EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo2Name
        {
            get
            {
                return this.RelativeInfo2NameField;
            }
            set
            {
                this.RelativeInfo2NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInfo2Phone
        {
            get
            {
                return this.RelativeInfo2PhoneField;
            }
            set
            {
                this.RelativeInfo2PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint RelativeInfo2RelationId
        {
            get
            {
                return this.RelativeInfo2RelationIdField;
            }
            set
            {
                this.RelativeInfo2RelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResignationDate
        {
            get
            {
                return this.ResignationDateField;
            }
            set
            {
                this.ResignationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salary
        {
            get
            {
                return this.SalaryField;
            }
            set
            {
                this.SalaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SeniorityDate
        {
            get
            {
                return this.SeniorityDateField;
            }
            set
            {
                this.SeniorityDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffCategory
        {
            get
            {
                return this.StaffCategoryField;
            }
            set
            {
                this.StaffCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdPartyUsername
        {
            get
            {
                return this.ThirdPartyUsernameField;
            }
            set
            {
                this.ThirdPartyUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkLocation
        {
            get
            {
                return this.WorkLocationField;
            }
            set
            {
                this.WorkLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkPercentage
        {
            get
            {
                return this.WorkPercentageField;
            }
            set
            {
                this.WorkPercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkTimeEnd
        {
            get
            {
                return this.WorkTimeEndField;
            }
            set
            {
                this.WorkTimeEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkTimeStart
        {
            get
            {
                return this.WorkTimeStartField;
            }
            set
            {
                this.WorkTimeStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccessInfo", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class UserAccessInfo : object
    {
        
        private ServiceReference1.RemotableIdOfint DepartmentIdField;
        
        private ServiceReference1.RemotableIdOfint[] UserRoleListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint[] UserRoleList
        {
            get
            {
                return this.UserRoleListField;
            }
            set
            {
                this.UserRoleListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum GenderTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeKeyInformationAnswer", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class EmployeeKeyInformationAnswer : object
    {
        
        private int AnswerGroupIdField;
        
        private int[] AnswerOptionsIdListField;
        
        private string CustomAnswerField;
        
        private System.Nullable<System.DateTime> DateTimeAnswerField;
        
        private int ParentAnswerOptionIdField;
        
        private int ParentQuestionIdField;
        
        private int QuestionGroupIdField;
        
        private int QuestionIdField;
        
        private int RowIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerGroupId
        {
            get
            {
                return this.AnswerGroupIdField;
            }
            set
            {
                this.AnswerGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AnswerOptionsIdList
        {
            get
            {
                return this.AnswerOptionsIdListField;
            }
            set
            {
                this.AnswerOptionsIdListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomAnswer
        {
            get
            {
                return this.CustomAnswerField;
            }
            set
            {
                this.CustomAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeAnswer
        {
            get
            {
                return this.DateTimeAnswerField;
            }
            set
            {
                this.DateTimeAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentAnswerOptionId
        {
            get
            {
                return this.ParentAnswerOptionIdField;
            }
            set
            {
                this.ParentAnswerOptionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentQuestionId
        {
            get
            {
                return this.ParentQuestionIdField;
            }
            set
            {
                this.ParentQuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionGroupId
        {
            get
            {
                return this.QuestionGroupIdField;
            }
            set
            {
                this.QuestionGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId
        {
            get
            {
                return this.QuestionIdField;
            }
            set
            {
                this.QuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowId
        {
            get
            {
                return this.RowIdField;
            }
            set
            {
                this.RowIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.BatchSyncStatusResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetBatchSyncEmployeesStatusRsp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.BatchSyncEmployeesRsp))]
    public partial class ResponseBase : object
    {
        
        private string ReferenceTokenField;
        
        private ServiceReference1.SystemLanguageTypes SystemLanguageTypeField;
        
        private ServiceReference1.TransactionStatus TransactionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceToken
        {
            get
            {
                return this.ReferenceTokenField;
            }
            set
            {
                this.ReferenceTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SystemLanguageTypes SystemLanguageType
        {
            get
            {
                return this.SystemLanguageTypeField;
            }
            set
            {
                this.SystemLanguageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TransactionStatus TransactionStatus
        {
            get
            {
                return this.TransactionStatusField;
            }
            set
            {
                this.TransactionStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class TransactionStatus : object
    {
        
        private ServiceReference1.Customer CustomerField;
        
        private ServiceReference1.DebugOverview DebugOverviewField;
        
        private string StatusDescriptionField;
        
        private ServiceReference1.TransactionStatusTypes StatusTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                this.CustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DebugOverview DebugOverview
        {
            get
            {
                return this.DebugOverviewField;
            }
            set
            {
                this.DebugOverviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TransactionStatusTypes StatusType
        {
            get
            {
                return this.StatusTypeField;
            }
            set
            {
                this.StatusTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncStatusResponseBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetBatchSyncEmployeesStatusRsp))]
    public partial class BatchSyncStatusResponseBase : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.BatchSyncStatusTypes BatchSyncStatusTypeField;
        
        private ServiceReference1.BatchSyncEntityStatus[] EntitySyncStatusListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BatchSyncStatusTypes BatchSyncStatusType
        {
            get
            {
                return this.BatchSyncStatusTypeField;
            }
            set
            {
                this.BatchSyncStatusTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BatchSyncEntityStatus[] EntitySyncStatusList
        {
            get
            {
                return this.EntitySyncStatusListField;
            }
            set
            {
                this.EntitySyncStatusListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBatchSyncEmployeesStatusRsp", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class GetBatchSyncEmployeesStatusRsp : ServiceReference1.BatchSyncStatusResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncEmployeesRsp", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class BatchSyncEmployeesRsp : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.BatchSyncStatusTypes BatchSyncStatusTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BatchSyncStatusTypes BatchSyncStatusType
        {
            get
            {
                return this.BatchSyncStatusTypeField;
            }
            set
            {
                this.BatchSyncStatusTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncStatusTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum BatchSyncStatusTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknonw = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registered = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredWithErrors = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Overruled = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnderProcessing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedWithErrors = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class Customer : object
    {
        
        private ServiceReference1.CustomerDetails DetailsField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CustomerDetails Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebugOverview", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class DebugOverview : object
    {
        
        private string ExceptionDetailsField;
        
        private string ProcessingServerNameField;
        
        private long TotalMillisecondsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDetails
        {
            get
            {
                return this.ExceptionDetailsField;
            }
            set
            {
                this.ExceptionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessingServerName
        {
            get
            {
                return this.ProcessingServerNameField;
            }
            set
            {
                this.ProcessingServerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalMilliseconds
        {
            get
            {
                return this.TotalMillisecondsField;
            }
            set
            {
                this.TotalMillisecondsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatusTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum TransactionStatusTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedWithErrors = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDetails", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class CustomerDetails : ServiceReference1.RemotableEntityDetailsBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemotableEntityDetailsBase", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.CustomerDetails))]
    public partial class RemotableEntityDetailsBase : object
    {
        
        private ServiceReference1.RemotableIdOfint CreatedByUserIdField;
        
        private System.DateTime CreatedDateTimeUtcField;
        
        private ServiceReference1.RemotableIdOfint DeletedByUserIdField;
        
        private System.DateTime DeletedDateTimeUtcField;
        
        private ServiceReference1.PropertyBag PropertyBagField;
        
        private ServiceReference1.RemotableIdOfint UpdatedByUserIdField;
        
        private System.DateTime UpdatedDateTimeUtcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTimeUtc
        {
            get
            {
                return this.CreatedDateTimeUtcField;
            }
            set
            {
                this.CreatedDateTimeUtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint DeletedByUserId
        {
            get
            {
                return this.DeletedByUserIdField;
            }
            set
            {
                this.DeletedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeletedDateTimeUtc
        {
            get
            {
                return this.DeletedDateTimeUtcField;
            }
            set
            {
                this.DeletedDateTimeUtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PropertyBag PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint UpdatedByUserId
        {
            get
            {
                return this.UpdatedByUserIdField;
            }
            set
            {
                this.UpdatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDateTimeUtc
        {
            get
            {
                return this.UpdatedDateTimeUtcField;
            }
            set
            {
                this.UpdatedDateTimeUtcField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PropertyBag", Namespace="http://schemas.hr-manager.net/remoting/1.0/", ItemName="Property")]
    public class PropertyBag : System.Collections.Generic.List<ServiceReference1.Property>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class Property : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncEntityStatus", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public partial class BatchSyncEntityStatus : object
    {
        
        private string DescriptionField;
        
        private ServiceReference1.RemotableIdOfint EntityIdField;
        
        private ServiceReference1.BatchSyncEntityStatusTypes EntitySyncStatusTypeField;
        
        private ServiceReference1.BatchSyncEntityTypes EntityTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RemotableIdOfint EntityId
        {
            get
            {
                return this.EntityIdField;
            }
            set
            {
                this.EntityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BatchSyncEntityStatusTypes EntitySyncStatusType
        {
            get
            {
                return this.EntitySyncStatusTypeField;
            }
            set
            {
                this.EntitySyncStatusTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BatchSyncEntityTypes EntityType
        {
            get
            {
                return this.EntityTypeField;
            }
            set
            {
                this.EntityTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncEntityStatusTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum BatchSyncEntityStatusTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreatedWithNote = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotCreated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdatedWithNote = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotUpdated = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletedWithNote = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDeleted = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchSyncEntityTypes", Namespace="http://schemas.hr-manager.net/remoting/1.0/")]
    public enum BatchSyncEntityTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Project = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Name="Talent-Manger-Remoting-Service", Namespace="http://schemas.hr-manager.net/remoting/1.0/", ConfigurationName="ServiceReference1.TalentMangerRemotingService")]
    public interface TalentMangerRemotingService
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.hr-manager.net/remoting/1.0/IRemotingService/BatchSyncEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.BatchSyncEmployeesRsp> BatchSyncEmployeesAsync(ServiceReference1.BatchSyncEmployeesRqt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.hr-manager.net/remoting/1.0/IRemotingService/GetBatchSyncEmployees" +
            "Status", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBatchSyncEmployeesStatusRsp> GetBatchSyncEmployeesStatusAsync(ServiceReference1.GetBatchSyncEmployeesStatusRqt request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface TalentMangerRemotingServiceChannel : ServiceReference1.TalentMangerRemotingService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TalentMangerRemotingServiceClient : System.ServiceModel.ClientBase<ServiceReference1.TalentMangerRemotingService>, ServiceReference1.TalentMangerRemotingService
    {
        
        public TalentMangerRemotingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BatchSyncEmployeesRsp> BatchSyncEmployeesAsync(ServiceReference1.BatchSyncEmployeesRqt request)
        {
            return base.Channel.BatchSyncEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBatchSyncEmployeesStatusRsp> GetBatchSyncEmployeesStatusAsync(ServiceReference1.GetBatchSyncEmployeesStatusRqt request)
        {
            return base.Channel.GetBatchSyncEmployeesStatusAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
